input : "/omics/groups/OE0219/internal/Valentin/JMMLT/processing/quality_assessment/test.csv"
OUTDIR: "/omics/groups/OE0219/internal/Valentin/JMMLT/processing/quality_assessment"
REFERENCE: "/omics/groups/OE0219/internal/Valentin/genomes/hg38_ensembl/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa"
FASTQ_EXTENSIONS:
  - "fastq.gz"
  - "fastq"
  - "fq"
  - "fq.gz"
BAM_EXTENSIONS:
  - "bam"
